/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./components/AccountForm.vue')['default']
    AchievementsList: typeof import('./components/AchievementsList.vue')['default']
    AdOptions: typeof import('./components/AdOptions.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Badges: typeof import('./components/Badges.vue')['default']
    copy: typeof import('./components/StoreList copy.vue')['default']
    CustomTabs: typeof import('./components/CustomTabs.vue')['default']
    FavoriteCampaignCard: typeof import('./components/FavoriteCampaignCard.vue')['default']
    'Friend&StoreList': typeof import('./components/Friend&StoreList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NavegationBar: typeof import('./components/NavegationBar.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    Privacy: typeof import('./components/Privacy.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsCard: typeof import('./components/StatisticsCard.vue')['default']
    StoreList: typeof import('./components/StoreList.vue')['default']
    StoreListAdded: typeof import('./components/StoreListAdded.vue')['default']
    TabsComponent: typeof import('./components/TabsComponent.vue')['default']
    'TabsComponent.vue': typeof import('./components/TabsComponent.vue.vue')['default']
  }
}
