/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/Perfil': RouteRecordInfo<'/Perfil', '/Perfil', Record<never, never>, Record<never, never>>,
    '/Perfil_FS': RouteRecordInfo<'/Perfil_FS', '/Perfil_FS', Record<never, never>, Record<never, never>>,
    '/Perfil_FS-LIST': RouteRecordInfo<'/Perfil_FS-LIST', '/Perfil_FS-LIST', Record<never, never>, Record<never, never>>,
    '/Perfil-Settings': RouteRecordInfo<'/Perfil-Settings', '/Perfil-Settings', Record<never, never>, Record<never, never>>,
  }
}
